spring:
  thymeleaf:
    prefix: classpath:/static/
    cache: false
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bms?autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    username: root
    password: laij082699
    #初始化连接
    initialSize: 2
    #最大连接数量
    maxActive: 20
    #最大空闲连接
    maxIdle: 1
    #最小空闲连接
    minIdle: 5
  redis:
    database: 0
    host: 10.139.105.224
    port: 6381
    password:
    timeout: 30000
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 16

logging:
  config: logback.xml
#  level:
#    org:
#      springframework:
#        web: INFO
#        boot: INFO


shiro:
  #是否启用验证码
  ifNeedCaptcha: false
  #重复提交间隔时间(秒)
  repeatTime: 3
  #默认密码
  defaultPassword: bms123
  #登录超时时间(分钟)
  outTime: 30
  #散列算法名称
  hashAlgorithmName: MD5
  #散列迭代次数
  hashIterations: 1000
  #锁定时间（单位：分钟）
  time: 1
  #密码重试次数
  times: 5
  #密码有效时间（单位：月）
  passwordEffectiveTime: 3
  #密码最小长度
  minLength: 6
  #密码最大长度
  maxLength: 16
  #必须包含大写字母
  mustContainUpperCase: true
  #必须包含小写字母
  mustContainLowerCase: true
  #必须包含数字
  mustContainDigit: true

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    default-statement-timeout: 60
  mapper-locations: classpath*:com/bms/**/*Mapper.xml

server:
  port: 8888
  context-path: /bms
